/**
 * Design System Bridge — 02_Web_Application
 *
 * Re-exports all 57 UI components from 05_UI_Design_System.
 * Use @/ds-components/* (tsconfig path alias) for direct imports.
 * Use this file for barrel imports when you need multiple components at once.
 *
 * Token chain:
 *   Design_Tokens.json → globals.css (CSS vars) → Tailwind → components
 */

export { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/ds-components/ui/accordion'
export { Alert, AlertDescription, AlertTitle } from '@/ds-components/ui/alert'
export { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/ds-components/ui/alert-dialog'
export { AspectRatio } from '@/ds-components/ui/aspect-ratio'
export { Avatar, AvatarFallback, AvatarImage } from '@/ds-components/ui/avatar'
export { Badge, badgeVariants } from '@/ds-components/ui/badge'
export { Breadcrumb, BreadcrumbEllipsis, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from '@/ds-components/ui/breadcrumb'
export { Button, buttonVariants } from '@/ds-components/ui/button'
export { ButtonGroup } from '@/ds-components/ui/button-group'
export { Calendar } from '@/ds-components/ui/calendar'
export { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/ds-components/ui/card'
export { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from '@/ds-components/ui/carousel'
export { ChartContainer, ChartLegend, ChartLegendContent, ChartStyle, ChartTooltip, ChartTooltipContent } from '@/ds-components/ui/chart'
export { Checkbox } from '@/ds-components/ui/checkbox'
export { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/ds-components/ui/collapsible'
export { Command, CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList, CommandSeparator, CommandShortcut } from '@/ds-components/ui/command'
export { ContextMenu, ContextMenuCheckboxItem, ContextMenuContent, ContextMenuGroup, ContextMenuItem, ContextMenuLabel, ContextMenuPortal, ContextMenuRadioGroup, ContextMenuRadioItem, ContextMenuSeparator, ContextMenuShortcut, ContextMenuSub, ContextMenuSubContent, ContextMenuSubTrigger, ContextMenuTrigger } from '@/ds-components/ui/context-menu'
export { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/ds-components/ui/dialog'
export { Drawer, DrawerClose, DrawerContent, DrawerDescription, DrawerFooter, DrawerHeader, DrawerOverlay, DrawerPortal, DrawerTitle, DrawerTrigger } from '@/ds-components/ui/drawer'
export { DropdownMenu, DropdownMenuCheckboxItem, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuLabel, DropdownMenuPortal, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuShortcut, DropdownMenuSub, DropdownMenuSubContent, DropdownMenuSubTrigger, DropdownMenuTrigger } from '@/ds-components/ui/dropdown-menu'
export { Empty } from '@/ds-components/ui/empty'
export { Field } from '@/ds-components/ui/field'
export { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from '@/ds-components/ui/form'
export { HoverCard, HoverCardContent, HoverCardTrigger } from '@/ds-components/ui/hover-card'
export { Input } from '@/ds-components/ui/input'
export { InputGroup } from '@/ds-components/ui/input-group'
export { InputOTP, InputOTPGroup, InputOTPSeparator, InputOTPSlot } from '@/ds-components/ui/input-otp'
export { Item } from '@/ds-components/ui/item'
export { Kbd } from '@/ds-components/ui/kbd'
export { Label } from '@/ds-components/ui/label'
export { Menubar, MenubarCheckboxItem, MenubarContent, MenubarGroup, MenubarItem, MenubarLabel, MenubarMenu, MenubarPortal, MenubarRadioGroup, MenubarRadioItem, MenubarSeparator, MenubarShortcut, MenubarSub, MenubarSubContent, MenubarSubTrigger, MenubarTrigger } from '@/ds-components/ui/menubar'
export { NavigationMenu, NavigationMenuContent, NavigationMenuIndicator, NavigationMenuItem, NavigationMenuLink, NavigationMenuList, NavigationMenuTrigger, NavigationMenuViewport } from '@/ds-components/ui/navigation-menu'
export { Pagination, PaginationContent, PaginationEllipsis, PaginationItem, PaginationLink, PaginationNext, PaginationPrevious } from '@/ds-components/ui/pagination'
export { Popover, PopoverContent, PopoverTrigger } from '@/ds-components/ui/popover'
export { Progress } from '@/ds-components/ui/progress'
export { RadioGroup, RadioGroupItem } from '@/ds-components/ui/radio-group'
export { ResizableHandle, ResizablePanel, ResizablePanelGroup } from '@/ds-components/ui/resizable'
export { ScrollArea, ScrollBar } from '@/ds-components/ui/scroll-area'
export { Select, SelectContent, SelectGroup, SelectItem, SelectLabel, SelectSeparator, SelectTrigger, SelectValue } from '@/ds-components/ui/select'
export { Separator } from '@/ds-components/ui/separator'
export { Sheet, SheetClose, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle, SheetTrigger } from '@/ds-components/ui/sheet'
export { Skeleton } from '@/ds-components/ui/skeleton'
export { Slider } from '@/ds-components/ui/slider'
export { Toaster as SonnerToaster } from '@/ds-components/ui/sonner'
export { Spinner } from '@/ds-components/ui/spinner'
export { Switch } from '@/ds-components/ui/switch'
export { Table, TableBody, TableCaption, TableCell, TableFooter, TableHead, TableHeader, TableRow } from '@/ds-components/ui/table'
export { Tabs, TabsContent, TabsList, TabsTrigger } from '@/ds-components/ui/tabs'
export { Textarea } from '@/ds-components/ui/textarea'
export { Toast, ToastAction, ToastClose, ToastDescription, ToastProvider, ToastTitle, ToastViewport } from '@/ds-components/ui/toast'
export { Toaster } from '@/ds-components/ui/toaster'
export { Toggle, toggleVariants } from '@/ds-components/ui/toggle'
export { ToggleGroup, ToggleGroupItem } from '@/ds-components/ui/toggle-group'
export { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/ds-components/ui/tooltip'
